// <auto-generated />
namespace LMS.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Changed_Document_to_allow_uploads : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Changed_Document_to_allow_uploads));
        
        string IMigrationMetadata.Id
        {
            get { return "201607070746523_Changed_Document_to_allow_uploads"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
